### ISSUE TITLE
フロントエンド (javascript?) とバックエンド (python) を連携する

### ISSUE THREAD

**Issue by tnaoki0630** [tune0321/expense#2]
- GUI の言語は javascript でもなんでもいい。
- バックエンドは画像認識したいので、python がよさそう。

**Comment by tnaoki0630** [comment]
プロジェクトの構成を見直したほうがいいかも？

Copyml-web-app/
├── docker-compose.yml
├── backend/
│   ├── Dockerfile
│   ├── requirements.txt
│   ├── app.py
│   └── .dockerignore
└── frontend/
    ├── Dockerfile
    ├── package.json
    └── .dockerignore

**Comment by tune0321** [comment]
フロントとバックのフォルダを分けれたので一旦完了
